<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <StaticWebAssetBasePath>/</StaticWebAssetBasePath>
  </PropertyGroup>

  <PropertyGroup>
    <Product>Umbraco.Community.SearchEngineTools</Product>
    <PackageId>Umbraco.Community.SearchEngineTools</PackageId>
    <Title>Search Engine Tools</Title>
    <Description>A collection of properties and tools to enhance Search Engine Optimization and general Search Engine tasks. Developers are able to pick and choose which tools and properties they want to use.</Description>
    <PackageTags>umbraco; seo; search-engine; umbraco-marketplace; </PackageTags>
    <Authors>Game Info Sites</Authors>
    <Copyright>$([System.DateTime]::UtcNow.ToString(`yyyy`)) © Game Info Sites</Copyright>
    <PackageProjectUrl>https://github.com/Game-Info-Sites/Search-Engine-Tools</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Game-Info-Sites/Search-Engine-Tools</RepositoryUrl>
    <PackageReadmeFile>README_nuget.md</PackageReadmeFile>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageIcon></PackageIcon>
    <Version>1.0.0-Beta</Version>
    <PackageReleaseNotes>Beta release of core componantes.</PackageReleaseNotes>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Umbraco.Cms.Web.Website" />
    <PackageReference Include="Umbraco.Cms.Web.Common" />
    <PackageReference Include="Umbraco.Cms.Api.Common" />
    <PackageReference Include="Umbraco.Cms.Api.Management" />
  </ItemGroup>

  <ItemGroup>
    <!-- Dont include the client folder as part of packaging nuget build -->
    <Content Remove="Client\**" />

    <!-- However make the Umbraco-package.json included for dotnet pack or nuget package and visible to the solution -->
    <None Include="Client\public\umbraco-package.json" Pack="false" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\docs\README_nuget.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
