name: Release Package

# This action will start when a correctly formatted tag is pushed (e.g. 0.1.0)

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: src/SearchEngineTools/Client/package-lock.json

      - name: Build client
        working-directory: src/SearchEngineTools/Client
        run: |
          npm ci
          npm run build

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.0.x

      - name: Build & Pack
        run: dotnet pack src/SearchEngineTools/SearchEngineTools.csproj -c Release -o ./artifacts /p:Version=${{ github.ref_name }}

      - name: NuGet login (OIDC → temp key)
        uses: NuGet/login@v1
        id: nuget-login
        with:
          user: GameInfoSites

      - name: Push to NuGet
        run: dotnet nuget push "./artifacts/*.nupkg" -k ${{ steps.nuget-login.outputs.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
